export * from './src/client'
export * from './src/clinic'
export * from './src/schedule-default-week-time'
export * from './src/consultation'
export * from './src/payment-method'
export * from './src/discount'
export * from './src/transaction'
